---
- name: Check if Ubuntu OVA exists locally
  stat:
    path: "{{ temp_dir }}/{{ ubuntu_ova }}"
  register: file_check

- name: Download Ubuntu OVA (if OVA file doesn't exist locally)
  get_url:
    url:  "{{ ubuntu_ova_url_base }}{{ ubuntu_ova }}"
    dest: "{{ temp_dir }}/{{ ubuntu_ova }}"
  when:
    - file_check.stat.exists != true

- name: Check IP
  debug:
    msg: "VM IP: {{ ubuntu_client_ip_address }}"
    
- name: Deploy Ubuntu OVA
  vmware_deploy_ovf:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    validate_certs: no
    name: "{{ ubuntu_vm_name }}"
    cluster: "{{ cluster }}"
    datacenter: "{{ datacenter }}"
    datastore: "{{ datastore }}"
    disk_provisioning: thin
    networks: "{u'VM Network':u'{{ ubuntu_vm_network }}'}"
    ova: "{{ temp_dir }}/{{ ubuntu_ova }}" 
    allow_duplicates: no
    power_on: no
    fail_on_spec_warnings: no
    wait: yes
    wait_for_ip_address: yes
    inject_ovf_env: yes
    properties:
      user-data: "{{ lookup('template', 'cloud_init_config.j2') | b64encode }}"
  delegate_to: localhost
  register: vm_instance_data

- name: Get Ubuntu VM UUID 
  set_fact:
    vm_uuid: "{{ vm_instance_data.hw_product_uuid }}"

- name: Configure Ubuntu VM resources
  vmware_guest:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    validate_certs: no
    uuid: "{{ vm_uuid }}"
    state: "present"
    hardware:
      memory_mb: "{{ ubuntu_vm_memory }}"
      num_cpus: "{{ ubuntu_vm_cpus }}"
    disk: 
    - size_gb: "{{ ubuntu_vm_disk_size }}"
  delegate_to: "localhost"

- name: Power on Ubuntu VM
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcsa_hostname }}"
    username: "{{ vcsa_username }}"
    password: "{{ vcsa_password }}"
    validate_certs: no
    uuid: "{{ vm_uuid }}"
    state: powered-on
  delegate_to: localhost

- name: Wait for port 22 to become open and contain "OpenSSH"
  wait_for:
    port: 22
    host: "{{ ubuntu_client_ip_address | ansible.netcommon.ipaddr('address')  }}"
    search_regex: OpenSSH
    delay: 10