---
- name: install Docker CE dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  ignore_errors: yes

- name: Add an Docker CE Apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker CE PPA
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu "{{ ansible_distribution_release }}" stable
    mode: "0644"

- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
