---
- name: install aws cli dependencies
  apt:
    name:
      - python-dev
  ignore_errors: yes

- name: create temporary dir
  tempfile:
    state: directory
    suffix: -aws-cli
  register: temp_dir

- name: unpack aws cli archive
  unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "{{temp_dir.path}}"
    remote_src: true

- name: install aws cli 
  command: "{{temp_dir.path}}/aws/install --update"

- name: removing temporary dir
  file:
    path: "{{temp_dir.path}}"
    state: absent
