---
- name: get terraform release info
  uri:
    url: "https://checkpoint-api.hashicorp.com/v1/check/terraform"
    return_content: yes
    body_format: json
  register: release_info

- name: get latest download version
  set_fact:
    download_version: "{{ release_info.json | json_query(json_filter) | replace('v','') }}"
  vars:
    - json_filter: current_version
  when: terraform_cli.version is not defined

- name: get specified download version
  set_fact:
    download_version: "{{terraform_cli.version}}"
  when: terraform_cli.version is defined

- name: generate download url
  set_fact:
    cli_url: https://releases.hashicorp.com/terraform/{{download_version}}/terraform_{{download_version}}_linux_amd64.zip

- debug:
    msg: "terraform download url: {{cli_url}}"

- name: create temporary dir
  tempfile:
    state: directory
    suffix: -terraform-cli
  register: temp_dir

- name: download terraform cli archive
  get_url:
    url: "{{cli_url}}"
    dest: "{{temp_dir.path}}/terraform.zip"

- name: unpack terraform cli archive
  unarchive:
    src: "{{temp_dir.path}}/terraform.zip"
    dest: "{{terraform_cli.install_location}}"
    remote_src: true

- name: delete temporary dir
  file:
    state: absent
    path: "{{temp_dir.path}}/"
