---
- name: get packer release info
  uri:
    url: "https://checkpoint-api.hashicorp.com/v1/check/packer"
    return_content: yes
    body_format: json
  register: release_info

- name: get latest download version
  set_fact:
    download_version: "{{ release_info.json | json_query(json_filter) | replace('v','') }}"
  vars:
    - json_filter: current_version
  when: packer_cli.version is not defined

- name: get specified download version
  set_fact:
    download_version: "{{packer_cli.version}}"
  when: packer_cli.version is defined

- name: generate download url
  set_fact:
    cli_url: https://releases.hashicorp.com/packer/{{download_version}}/packer_{{download_version}}_linux_amd64.zip

- debug:
    msg: "packer download url: {{cli_url}}"

- name: create temporary dir
  tempfile:
    state: directory
    suffix: -packer-cli
  register: temp_dir

- name: download packer cli archive
  get_url:
    url: "{{cli_url}}"
    dest: "{{temp_dir.path}}/packer.zip"

- name: unpack packer cli archive
  unarchive:
    src: "{{temp_dir.path}}/packer.zip"
    dest: "{{packer_cli.install_location}}"
    remote_src: true

- name: delete temporary dir
  file:
    state: absent
    path: "{{temp_dir.path}}/"
