---
- name: install keychain
  apt:
    name: keychain

- name: install zsh
  apt:
    name: zsh

- name: delete oh-my-zsh installation
  file:
    path: /home/{{ local_user }}/.oh-my-zsh
    state: absent

- name: download oh-my-zsh installer
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/zsh-installer.sh
    mode: 0755

- name: execute the oh-my-zsh installer
  become_user: "{{ local_user }}"
  shell: /tmp/zsh-installer.sh --unattended

- name: remove the oh-my-zsh installer
  file:
    path: /tmp/zsh-installer.sh
    state: absent

- name: install powerlevel10k
  become_user: "{{ local_user }}"
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/{{ local_user }}/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1

- name: setup zsh
  become_user: "{{ local_user }}"
  template:
    src: files/.zshrc.j2
    dest: /home/{{ local_user }}/.zshrc

- name: setup powerlevel10k
  become_user: "{{ local_user }}"
  copy:
    src: files/.p10k.zsh
    dest: /home/{{ local_user }}/.p10k.zsh

- name: change user shell to zsh 
  become_user: "{{ local_user }}"
  user:
    name: "{{ local_user }}"
    shell: /bin/zsh